/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package karyawanku.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import karyawanku.DB.Karyawan;
import karyawanku.utils.Formatter;
import karyawanku.utils.PrintPdf;

/**
 *
 * @author muhammadarya
 */
public class FrameDataKaryawan extends javax.swing.JFrame {

    private DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Nama", "Jenis Kelamin", "Divisi", "Gaji"}, 0);
    private int id = 0;

    /**
     * Creates new form FrameDataKaryawan
     */
    public FrameDataKaryawan() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadDataTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKaryawan = new javax.swing.JTable();
        filterDivisi = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtGaji = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioP = new javax.swing.JRadioButton();
        radioL = new javax.swing.JRadioButton();
        cmbDivisi = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Karyawan");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(77, 161, 169));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelKaryawan.setModel(model);
        tabelKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKaryawan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 237, 720, 340));

        filterDivisi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        filterDivisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Divisi", "Human Resource", "Keuangan", "IT", "Pemasaran" }));
        jPanel1.add(filterDivisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 210, 30));

        txtCari.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 210, 30));

        btnHapus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 130, 30));

        btnEdit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEdit.setText("Ubah");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 130, 30));

        btnTambah.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 130, 30));

        btnCari.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 80, 30));

        txtGaji.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txtGaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 250, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Divisi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gaji");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jenis Kelamin");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        groupGender.add(radioP);
        radioP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radioP.setForeground(new java.awt.Color(255, 255, 255));
        radioP.setText("Perempuan");
        jPanel1.add(radioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        groupGender.add(radioL);
        radioL.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radioL.setForeground(new java.awt.Color(255, 255, 255));
        radioL.setText("Laki-laki");
        jPanel1.add(radioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        cmbDivisi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbDivisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Divisi", "Human Resource", "Keuangan", "IT", "Pemasaran" }));
        jPanel1.add(cmbDivisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 250, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Lengkap");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        txtNama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 250, 30));

        btnFilter.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFilter.setText("Filter");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        jPanel1.add(btnFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 80, 30));

        btnKembali.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnKembali.setText("Kembali ke Frame Utama");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 300, 40));

        btnRefresh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 130, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try {
            String nama = txtNama.getText();
            Double gaji = Double.parseDouble(txtGaji.getText());
            String gender = "";
            String divisi = (String) cmbDivisi.getSelectedItem();

            if (radioL.isSelected()) {
                gender = "L";
            } else if (radioP.isSelected()) {
                gender = "P";
            }
            // Validasi Input
            if (nama.isEmpty() || gaji == 0 || gender.isEmpty() || divisi.equals("Pilih Divisi")) {
                JOptionPane.showMessageDialog(this, "Masukkan data dengan benar", "Gagal", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                // Insert Data
                Karyawan.insert(nama, gender, divisi, gaji);
                JOptionPane.showMessageDialog(this, "Berhasil menginput data", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                clearInput();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Masukkan data dengan benar", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
        loadDataTabel();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (this.id == 0) {
            JOptionPane.showMessageDialog(this, "Silahkan klik data yang ingin diedit terlebih dahulu", "Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            try {
                String nama = txtNama.getText();
                Double gaji = Double.parseDouble(txtGaji.getText());
                String gender = "";
                String divisi = (String) cmbDivisi.getSelectedItem();

                if (radioL.isSelected()) {
                    gender = "L";
                } else if (radioP.isSelected()) {
                    gender = "P";
                }
                // Validasi Input
                if (nama.isEmpty() || gaji == 0 || gender.isEmpty() || divisi.equals("Pilih Divisi")) {
                    JOptionPane.showMessageDialog(this, "Masukkan data dengan benar", "Gagal", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                // Update Data
                boolean berhasilUpdate = Karyawan.update(this.id, nama, gender, divisi, gaji);
                if (berhasilUpdate) {
                    JOptionPane.showMessageDialog(this, "Berhasil Mengupdate data", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal Mengupdate data", "Gagal", JOptionPane.WARNING_MESSAGE);
                }
                loadDataTabel();
                clearInput();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Masukkan data dengan benar", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
        System.out.println("ID: " + this.id);
    }//GEN-LAST:event_btnEditActionPerformed

    private void tabelKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKaryawanMouseClicked
        // TODO add your handling code here:
        int row = tabelKaryawan.getSelectedRow();
        this.id = Integer.parseInt(tabelKaryawan.getValueAt(row, 0).toString());
        Object[] karyawan = Karyawan.getData(this.id);
        if (karyawan == null) {
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan", "Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // set data to inputfield
        String gender = (String) karyawan[2];
        txtNama.setText((String) karyawan[1]);
        txtGaji.setText("" + karyawan[4]);
        if (gender.equals("L")) {
            radioL.setSelected(true);
        } else if (gender.equals("P")) {
            radioP.setSelected(true);
        }
        cmbDivisi.setSelectedItem(karyawan[3]);
    }//GEN-LAST:event_tabelKaryawanMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (this.id == 0) {
            JOptionPane.showMessageDialog(this, "Silahkan klik data yang ingin dihapus terlebih dahulu", "Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }
        boolean berhasilHapus = Karyawan.delete(this.id);
        if (berhasilHapus) {
            JOptionPane.showMessageDialog(this, "Berhasil Menghapus data", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Menghapus data", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
        clearInput();
        loadDataTabel();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadDataTabel();
        clearInput();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrameUtama().setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        this.id = 0;
        String divisi = (String) filterDivisi.getSelectedItem();
        if (filterDivisi.getSelectedIndex() == 0) {
            divisi = "";
        }
        ArrayList<Object[]> data = Karyawan.getAllData(divisi);
        for (Object[] item : data) {
            item[4] = Formatter.formatRupiah((Double) item[4]);
            item[2] = ((String) item[2]).equals("L") ? "Laki-laki" : "Perempuan";
            model.addRow(item);
        }
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        this.id = 0;
        String inputSearch = txtCari.getText();
        ArrayList<Object[]> data = Karyawan.getDataByName(inputSearch);
        for (Object[] item : data) {
            item[2] = ((String) item[2]).equals("L") ? "Laki-laki" : "Perempuan";
            item[4] = Formatter.formatRupiah((Double) item[4]);
            model.addRow(item);
        }

    }//GEN-LAST:event_btnCariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean berhasilCetak = PrintPdf.print();
        if (berhasilCetak) {
            JOptionPane.showMessageDialog(this, "Berhasil mengekspor data", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengekspor data", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearInput() {
        this.id = 0;
        txtNama.setText("");
        txtGaji.setText("");
        txtCari.setText("");
        cmbDivisi.setSelectedIndex(0);
        filterDivisi.setSelectedIndex(0);
        groupGender.clearSelection();

    }

    private void loadDataTabel() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        this.id = 0;
        ArrayList<Object[]> data = Karyawan.getAllData();

        for (Object[] item : data) {
            item[4] = Formatter.formatRupiah((Double) item[4]);
            item[2] = ((String) item[2]).equals("L") ? "Laki-laki" : "Perempuan";
            model.addRow(item);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbDivisi;
    private javax.swing.JComboBox<String> filterDivisi;
    private javax.swing.ButtonGroup groupGender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioL;
    private javax.swing.JRadioButton radioP;
    private javax.swing.JTable tabelKaryawan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
